import pm4py
import pandas as pd
import hashlib
import os
import tempfile
from services.db import db
from services.models import BpmnFile, ConsolidatedEvent
from services.bpmn_service import save_bpmn
from datetime import datetime
from pm4py.objects.bpmn.exporter import exporter as bpmn_exporter
from sqlalchemy.exc import SQLAlchemyError

def get_csv(project_id):
    try:
        events = ConsolidatedEvent.query.filter_by(project_id=project_id).all()
        if not events:
            return []
        rows = [
            {
                "id": e.id,
                "merge_run_id": e.merge_run_id,
                "project_id": e.project_id,
                "case_id": e.case_id,
                "activity": e.activity,
                "canonical_activity": e.canonical_activity,
                "timestamp": e.timestamp,
                "source": e.source,
            } for e in events
        ]
        return rows
    except Exception as e:
        raise RuntimeError(f"Failed to fetch consolidated events: {e}")

def mine_process_from_csv(user_id, project_id, name="untitled", description=""):
    temp_file = tempfile.NamedTemporaryFile(suffix=".bpmn", delete=False)
    temp_file_path = temp_file.name
    temp_file.close()

    try:
        file = get_csv(project_id)
        dataframe = pd.DataFrame(file)

        if dataframe.empty:
            raise RuntimeError("No consolidated events found to mine.")

        # --- Prefer canonical labels when present, else fall back to raw activity ---
        # Treat empty/NaN canonical labels as missing
        canon = dataframe.get("canonical_activity")
        if canon is not None:
            canon = canon.astype("string")
        dataframe["__label__"] = canon.where(
            canon.notna() & (canon.str.strip() != ""),
            dataframe["activity"].astype("string")
        )

        # Format & mine using the resolved label column
        dataframe = pm4py.format_dataframe(
            dataframe,
            case_id="case_id",
            activity_key="__label__",
            timestamp_key="timestamp"
        )
        bpmn_diagram = pm4py.discover_bpmn_inductive(
            dataframe,
            case_id_key="case_id",
            activity_key="__label__",
            timestamp_key="timestamp"
        )

        bpmn_exporter.apply(bpmn_diagram, temp_file_path)
        with open(temp_file_path, "rb") as f:
            xml_bytes_raw = f.read()

        # Preserve your original comment behavior, but avoid str/bytes confusion
        xml_str_with_comment = b"<!-- generated by pm4py -->\n" + xml_bytes_raw
        xml_bytes = xml_str_with_comment

        xml = xml_bytes.decode("utf-8", errors="ignore")
        new_bpmn = save_bpmn(
            user_id=user_id,
            project_id=project_id,
            name=name,
            description=description,
            xml=xml
        )

        return new_bpmn

    except SQLAlchemyError as e:
        db.session.rollback()
        raise RuntimeError(f"Database error: {e}")

    except Exception as e:
        db.session.rollback()
        raise RuntimeError(f"Process mining failed: {e}")

    finally:
        if os.path.exists(temp_file_path):
            os.remove(temp_file_path)
